// Headless test: full Vanilla install pipeline without GUI.
// Validates manifest fetch, version metadata, client JAR, libraries and asset
// index against the real Mojang network using the same classes as the
// launcher. Run with QT_QPA_PLATFORM=offscreen.
#include "services/download_manager.h"
#include "services/minecraft_install_service.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QJsonObject>
#include <cstdio>

// moc is generated by AUTOMOC into the build directory; the include resolves
// through AUTOMOC-generated source files rather than this file's directory.

static constexpr auto kManifestUrl = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json";

class PipelineProbe : public QObject {
    Q_OBJECT
public:
    PipelineProbe(const QString &workDir, const QString &versionId)
        : m_workDir(workDir), m_versionId(versionId)
    {
        m_downloadManager = new atlas::DownloadManager(this);
        m_installService = new atlas::MinecraftInstallService(m_workDir + QStringLiteral("/game"), m_downloadManager, this);
        connect(m_installService, &atlas::MinecraftInstallService::installStarted,
                this, &PipelineProbe::onInstallStarted);
        connect(m_installService, &atlas::MinecraftInstallService::installFinished,
                this, &PipelineProbe::onInstallFinished);
        connect(m_installService, &atlas::MinecraftInstallService::installError,
                this, &PipelineProbe::onInstallError);
        connect(m_installService, &atlas::MinecraftInstallService::versionsReady,
                this, &PipelineProbe::onVersionsReady);
        connect(m_installService, &atlas::MinecraftInstallService::versionsError,
                this, &PipelineProbe::onVersionsError);
        connect(m_downloadManager, &atlas::DownloadManager::taskChanged,
                this, &PipelineProbe::onTaskChanged);
    }

    void start()
    {
        // Запрашиваем все официальные категории: параметр версии может быть
        // release, snapshot, old_beta или old_alpha.
        m_installService->refreshVersions(true, true, true);
        m_timeoutTimer = startTimer(15 * 60 * 1000);
    }

private slots:
    void onVersionsError(const QString &error)
    {
        std::fprintf(stderr, "versionsError: %s\n", error.toUtf8().constData());
        m_exitCode = 3;
        QCoreApplication::quit();
    }

    void onVersionsReady(const QVector<atlas::MinecraftVersionDescriptor> &versions)
    {
        std::printf("manifest versions: %d\n", static_cast<int>(versions.size()));
        atlas::Instance instance;
        instance.id = QStringLiteral("vanilla-pipeline-test");
        instance.minecraftVersion = m_versionId;
        instance.loader.kind = atlas::LoaderKind::Vanilla;
        instance.rootPath = m_workDir + QStringLiteral("/game");
        m_installService->installVanilla(instance);
    }

    void onInstallStarted(const QString &, const QString &version)
    {
        std::printf("install started for %s\n", version.toUtf8().constData());
    }

    void onTaskChanged(const atlas::DownloadTask &task)
    {
        if (task.state == atlas::DownloadState::Completed) {
            std::printf("completed: %s (%lld bytes)\n",
                        task.request.title.toUtf8().constData(),
                        static_cast<long long>(task.bytesReceived));
            m_completedCount++;
        } else if (task.state == atlas::DownloadState::Failed) {
            std::fprintf(stderr, "failed: %s %s\n",
                         task.request.title.toUtf8().constData(),
                         task.error.toUtf8().constData());
            m_exitCode = 4;
            QCoreApplication::quit();
        }
    }

    void onInstallFinished(const QString &, const QString &version)
    {
        QString legacyError;
        if (!validateLegacyResources(version, &legacyError)) {
            std::fprintf(stderr, "legacy resources validation failed: %s\n", legacyError.toUtf8().constData());
            m_exitCode = 7;
            QCoreApplication::quit();
            return;
        }
        std::printf("install finished for %s; completed tasks: %lld\n",
                    version.toUtf8().constData(), static_cast<long long>(m_completedCount));
        m_exitCode = 0;
        QCoreApplication::quit();
    }

    void onInstallError(const QString &, const QString &error)
    {
        std::fprintf(stderr, "installError: %s\n", error.toUtf8().constData());
        m_exitCode = 5;
        QCoreApplication::quit();
    }

    bool validateLegacyResources(const QString &version, QString *error) const
    {
        // MinecraftInstallService получает data-dir `<work>/game` и использует
        // `<data-dir>/game` как корневой каталог Minecraft.
        const QString minecraftRoot = m_workDir + QStringLiteral("/game/game");
        QFile metadataFile(minecraftRoot + QStringLiteral("/versions/%1/%1.json").arg(version));
        if (!metadataFile.open(QIODevice::ReadOnly)) {
            if (error) *error = QStringLiteral("version metadata cannot be opened");
            return false;
        }
        const QJsonDocument metadata = QJsonDocument::fromJson(metadataFile.readAll());
        const QString assetId = metadata.object().value(QStringLiteral("assetIndex")).toObject()
            .value(QStringLiteral("id")).toString();
        if (assetId.isEmpty()) {
            if (error) *error = QStringLiteral("version metadata does not contain asset index id");
            return false;
        }
        QFile indexFile(minecraftRoot + QStringLiteral("/assets/indexes/%1.json").arg(assetId));
        if (!indexFile.open(QIODevice::ReadOnly)) {
            if (error) *error = QStringLiteral("asset index cannot be opened");
            return false;
        }
        const QJsonObject index = QJsonDocument::fromJson(indexFile.readAll()).object();
        if (!index.value(QStringLiteral("map_to_resources")).toBool(false)) return true;

        const QJsonObject objects = index.value(QStringLiteral("objects")).toObject();
        if (objects.isEmpty()) {
            if (error) *error = QStringLiteral("legacy asset index does not contain objects");
            return false;
        }
        const QString probeRelativePath = objects.constBegin().key();
        // map_to_resources относится к рабочей папке экземпляра, а не к
        // общему Minecraft-каталогу libraries/assets.
        const QString probePath = QDir(m_workDir + QStringLiteral("/game/resources")).filePath(probeRelativePath);
        if (!QFileInfo(probePath).isFile()) {
            if (error) *error = QStringLiteral("mapped legacy resource is missing: %1").arg(probePath);
            return false;
        }
        return true;
    }

    void timerEvent(QTimerEvent *) override
    {
        if (m_exitCode < 0) {
            std::fprintf(stderr, "pipeline timed out after 900s; completed tasks: %lld\n",
                         static_cast<long long>(m_completedCount));
            m_exitCode = 6;
            QCoreApplication::quit();
        }
        killTimer(m_timeoutTimer);
        m_timeoutTimer = -1;
    }

public:
    int exitCode() const { return m_exitCode; }

private:
    QString m_workDir;
    QString m_versionId;
    atlas::DownloadManager *m_downloadManager = nullptr;
    atlas::MinecraftInstallService *m_installService = nullptr;
    int m_timeoutTimer = -1;
    long long m_completedCount = 0;
    int m_exitCode = -1;
};

#include "vanilla_pipeline_test.moc"

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);
    if (app.arguments().size() < 3) {
        std::fprintf(stderr, "usage: %s <work-directory> <minecraft-version>\n", argv[0]);
        return 2;
    }
    PipelineProbe probe(app.arguments().at(1), app.arguments().at(2));
    probe.start();
    const int result = app.exec();
    return (result == 0 && probe.exitCode() >= 0) ? probe.exitCode() : result;
}
